♻️ feat: re-add ban refactor
Gunivers/Gipsy-plugins pull request #21
Opened 2022-11-12 19:18 UTC by Aeris1One

2022-11-12 21:11 UTC, Aeris1One commented
Il faut noter que la config marche pas correctement pour plusieurs raisons : 
- ça marche pas

2023-02-02 14:37 UTC, LeiRoF commented
I have an error when I try to start the bot on this PR

<details>
<summary> Logs </summary>

```
ENVIRONMENT: uname_result(system='Windows', node='VinceMateBook', release='10', version='10.0.22621', machine='AMD64')

02/02/2023 at 15:35:37 | [INFO] ▶️ Starting Gipsy...
02/02/2023 at 15:35:41 | [INFO] [32m✅ Bot connected
02/02/2023 at 15:35:41 | [INFO] Nom : Gipsy Dev
02/02/2023 at 15:35:41 | [INFO] ID : 786546781919641600
02/02/2023 at 15:35:41 | [INFO] Connected on 2 servers:
 - Gipsy Sandbox
 - T E S T
02/02/2023 at 15:35:41 | [ERROR] Failed to load extension: plugins.ban.ban
02/02/2023 at 15:35:41 | Full traceback below.

Traceback (most recent call last):
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\lib\site-packages\discord\ext\commands\bot.py", line 946, in _load_from_module_spec
    await setup(self)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 270, in setup
    await bot.add_cog(Ban(bot))
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 24, in __init__
    self.load_friendly_ban()
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 181, in load_friendly_ban
    self.friendly_ban_config = self.bot.config.get("friendly_ban", {})
AttributeError: 'Gunibot' object has no attribute 'config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\start.py", line 89, in load
    await bot_client.load_extension(extension)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\lib\site-packages\discord\ext\commands\bot.py", line 951, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'plugins.ban.ban' raised an error: AttributeError: 'Gunibot' object has no attribute 'config'
```

</details>

2023-02-04 12:42 UTC, Aeris1One commented
@ascpial can you fix this ? You can push directly into this PR's branch if you want.

2023-02-04 12:44 UTC, ascpial commented
Je vais voir ça, je mergerais ici alors (merci pour l'autorisation)

2023-02-11 16:20 UTC, Leirof requested changes
J'ai une erreur au démarrage du bot
<details>
<summary>Logs</summary>

```
ENVIRONMENT: uname_result(system='Windows', node='Vince-HeavyTower', release='10', version='10.0.22623', machine='AMD64')

11/02/2023 at 17:18:08 | [INFO] ▶️ Starting Gipsy...
11/02/2023 at 17:18:11 | [INFO] [32m✅ Bot connected
11/02/2023 at 17:18:11 | [INFO] Nom : Gipsy Dev
11/02/2023 at 17:18:11 | [INFO] ID : 786546781919641600
11/02/2023 at 17:18:11 | [INFO] Connected on 2 servers:
 - Gipsy Sandbox
 - T E S T
11/02/2023 at 17:18:11 | [ERROR] Failed to load extension: plugins.ban.ban
11/02/2023 at 17:18:11 | Full traceback below.

Traceback (most recent call last):
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\Lib\site-packages\discord\ext\commands\bot.py", line 946, in _load_from_module_spec
    await setup(self)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 277, in setup
    await bot.add_cog(Ban(bot))
                      ^^^^^^^^
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 31, in __init__
    self.load_friendly_ban()
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\ban\ban.py", line 188, in load_friendly_ban
    self.friendly_ban_config = self.bot.config.get("friendly_ban", {})
                               ^^^^^^^^^^^^^^^
AttributeError: 'Gunibot' object has no attribute 'config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\start.py", line 92, in load
    await bot_client.load_extension(extension)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\Lib\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\venv\Lib\site-packages\discord\ext\commands\bot.py", line 951, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'plugins.ban.ban' raised an error: AttributeError: 'Gunibot' object has no attribute 'config'

11/02/2023 at 17:18:12 | [INFO] 28 plugins loaded, 1 plugins failed
```

</details>

2023-02-11 16:53 UTC, ascpial commented
Prêt à être merge après tests par un tier 😉

2023-02-11 16:55 UTC, Leirof approved these changes
LGTM

2023-02-11 16:55 UTC, merged